item {
  id: 1
  name: 'adk_brown_dump'
}

item {
  id: 2
  name: 'adk_green_bare'
}

item {
  id: 3
  name: 'adk_green_dump'
}

item {
  id: 4
  name: 'adk_green_flat'
}

item {
  id: 5
  name: 'adk_green_flat10wh'
}

item {
  id: 6
  name: 'adk_green_semi'
}

item {
  id: 7
  name: 'adk_tan_flat'
}

item {
  id: 8
  name: 'armytruck'
}

item {
  id: 9
  name: 'forklift'
}

item {
  id: 10
  name: 'suv'
}

item {
  id: 11
  name: 'truck'
}

item {
  id: 12
  name: 'car'
}

item {
  id: 13
  name: 'adk_green_flat1'
}

item {
  id: 14
  name: 'adk_green_semi1'
}

item {
  id: 15
  name: 'gator'
}

item {
  id: 16
  name: 'adk_green_flat_10wh'
}

item {
  id: 17
  name: 'armytruck1'
}

item {
  id: 18
  name: 'armytruck2'
}

item {
  id: 19
  name: 'armytruck3'
}
